# Generated by Django 3.0.3 on 2020-02-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('emailAddress', models.EmailField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
